package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TOperationWechatCustomer;
import com.warrior.mercury.model.entity.auto.TOperationWechatCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOperationWechatCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    long countByExample(TOperationWechatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    int deleteByExample(TOperationWechatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer operationWechatCustomerID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    int insert(TOperationWechatCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    int insertSelective(TOperationWechatCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    List<TOperationWechatCustomer> selectByExample(TOperationWechatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    TOperationWechatCustomer selectByPrimaryKey(Integer operationWechatCustomerID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TOperationWechatCustomer record, @Param("example") TOperationWechatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TOperationWechatCustomer record, @Param("example") TOperationWechatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TOperationWechatCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TOperationWechatCustomer record);
}