package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TOperationWechatState;
import com.warrior.mercury.model.entity.auto.TOperationWechatStateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOperationWechatStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    long countByExample(TOperationWechatStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    int deleteByExample(TOperationWechatStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer operationWechatStateID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    int insert(TOperationWechatState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    int insertSelective(TOperationWechatState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    List<TOperationWechatState> selectByExample(TOperationWechatStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    TOperationWechatState selectByPrimaryKey(Integer operationWechatStateID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TOperationWechatState record, @Param("example") TOperationWechatStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TOperationWechatState record, @Param("example") TOperationWechatStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TOperationWechatState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TOperationWechatState record);
}