package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TOperationWechatUsingLog;
import com.warrior.mercury.model.entity.auto.TOperationWechatUsingLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TOperationWechatUsingLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    long countByExample(TOperationWechatUsingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    int deleteByExample(TOperationWechatUsingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer operationWechatUsingLogID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    int insert(TOperationWechatUsingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    int insertSelective(TOperationWechatUsingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    List<TOperationWechatUsingLog> selectByExample(TOperationWechatUsingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    TOperationWechatUsingLog selectByPrimaryKey(Integer operationWechatUsingLogID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TOperationWechatUsingLog record, @Param("example") TOperationWechatUsingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TOperationWechatUsingLog record, @Param("example") TOperationWechatUsingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TOperationWechatUsingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TOperationWechatUsingLog record);
}