package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TPhonePhoneNumberWechat;
import com.warrior.mercury.model.entity.auto.TPhonePhoneNumberWechatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhonePhoneNumberWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    long countByExample(TPhonePhoneNumberWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    int deleteByExample(TPhonePhoneNumberWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phonePhoneNumberWechatID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    int insert(TPhonePhoneNumberWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    int insertSelective(TPhonePhoneNumberWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    List<TPhonePhoneNumberWechat> selectByExample(TPhonePhoneNumberWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    TPhonePhoneNumberWechat selectByPrimaryKey(Integer phonePhoneNumberWechatID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhonePhoneNumberWechat record, @Param("example") TPhonePhoneNumberWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhonePhoneNumberWechat record, @Param("example") TPhonePhoneNumberWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhonePhoneNumberWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_number_wechat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhonePhoneNumberWechat record);
}