package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TPhoneusinglog;
import com.warrior.mercury.model.entity.auto.TPhoneusinglogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhoneusinglogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    long countByExample(TPhoneusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    int deleteByExample(TPhoneusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phoneUsingLogID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    int insert(TPhoneusinglog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    int insertSelective(TPhoneusinglog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    List<TPhoneusinglog> selectByExample(TPhoneusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    TPhoneusinglog selectByPrimaryKey(Integer phoneUsingLogID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhoneusinglog record, @Param("example") TPhoneusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhoneusinglog record, @Param("example") TPhoneusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhoneusinglog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneusinglog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhoneusinglog record);
}