package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TPhonePhoneNumerWechat;
import com.warrior.mercury.model.entity.auto.TPhonePhoneNumerWechatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhonePhoneNumerWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    long countByExample(TPhonePhoneNumerWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    int deleteByExample(TPhonePhoneNumerWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phonePhoneNumerWechatID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    int insert(TPhonePhoneNumerWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    int insertSelective(TPhonePhoneNumerWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    List<TPhonePhoneNumerWechat> selectByExample(TPhonePhoneNumerWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    TPhonePhoneNumerWechat selectByPrimaryKey(Integer phonePhoneNumerWechatID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhonePhoneNumerWechat record, @Param("example") TPhonePhoneNumerWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhonePhoneNumerWechat record, @Param("example") TPhonePhoneNumerWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhonePhoneNumerWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phone_phone_numer_wechat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhonePhoneNumerWechat record);
}