package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TPhonestate;
import com.warrior.mercury.model.entity.auto.TPhonestateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhonestateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    long countByExample(TPhonestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    int deleteByExample(TPhonestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phoneStateID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    int insert(TPhonestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    int insertSelective(TPhonestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    List<TPhonestate> selectByExample(TPhonestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    TPhonestate selectByPrimaryKey(Integer phoneStateID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhonestate record, @Param("example") TPhonestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhonestate record, @Param("example") TPhonestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhonestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonestate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhonestate record);
}