package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TPhonenumberstate;
import com.warrior.mercury.model.entity.auto.TPhonenumberstateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhonenumberstateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    long countByExample(TPhonenumberstateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    int deleteByExample(TPhonenumberstateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phoneNumberStateID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    int insert(TPhonenumberstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    int insertSelective(TPhonenumberstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    List<TPhonenumberstate> selectByExample(TPhonenumberstateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    TPhonenumberstate selectByPrimaryKey(Integer phoneNumberStateID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhonenumberstate record, @Param("example") TPhonenumberstateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhonenumberstate record, @Param("example") TPhonenumberstateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhonenumberstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberstate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhonenumberstate record);
}