package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TPhonenumberpurpose;
import com.warrior.mercury.model.entity.auto.TPhonenumberpurposeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhonenumberpurposeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    long countByExample(TPhonenumberpurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    int deleteByExample(TPhonenumberpurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phoneNumberPurposeID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    int insert(TPhonenumberpurpose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    int insertSelective(TPhonenumberpurpose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    List<TPhonenumberpurpose> selectByExample(TPhonenumberpurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    TPhonenumberpurpose selectByPrimaryKey(Integer phoneNumberPurposeID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhonenumberpurpose record, @Param("example") TPhonenumberpurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhonenumberpurpose record, @Param("example") TPhonenumberpurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhonenumberpurpose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberpurpose
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhonenumberpurpose record);
}