package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TPhonenumberusinglog;
import com.warrior.mercury.model.entity.auto.TPhonenumberusinglogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhonenumberusinglogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    long countByExample(TPhonenumberusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    int deleteByExample(TPhonenumberusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phoneNumberUsingLogID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    int insert(TPhonenumberusinglog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    int insertSelective(TPhonenumberusinglog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    List<TPhonenumberusinglog> selectByExample(TPhonenumberusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    TPhonenumberusinglog selectByPrimaryKey(Integer phoneNumberUsingLogID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhonenumberusinglog record, @Param("example") TPhonenumberusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhonenumberusinglog record, @Param("example") TPhonenumberusinglogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhonenumberusinglog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhonenumberusinglog record);
}