package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TPhoneoperatingsystem;
import com.warrior.mercury.model.entity.auto.TPhoneoperatingsystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhoneoperatingsystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    long countByExample(TPhoneoperatingsystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    int deleteByExample(TPhoneoperatingsystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phoneOperatingSystemID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    int insert(TPhoneoperatingsystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    int insertSelective(TPhoneoperatingsystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    List<TPhoneoperatingsystem> selectByExample(TPhoneoperatingsystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    TPhoneoperatingsystem selectByPrimaryKey(Integer phoneOperatingSystemID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhoneoperatingsystem record, @Param("example") TPhoneoperatingsystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhoneoperatingsystem record, @Param("example") TPhoneoperatingsystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhoneoperatingsystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhoneoperatingsystem record);
}