package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TPhonebrand;
import com.warrior.mercury.model.entity.auto.TPhonebrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhonebrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    long countByExample(TPhonebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    int deleteByExample(TPhonebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer phoneBrandID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    int insert(TPhonebrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    int insertSelective(TPhonebrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    List<TPhonebrand> selectByExample(TPhonebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    TPhonebrand selectByPrimaryKey(Integer phoneBrandID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhonebrand record, @Param("example") TPhonebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhonebrand record, @Param("example") TPhonebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhonebrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhonebrand record);
}