package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TWechatCustomerActivitySource;
import com.warrior.mercury.model.entity.auto.TWechatCustomerActivitySourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TWechatCustomerActivitySourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    long countByExample(TWechatCustomerActivitySourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    int deleteByExample(TWechatCustomerActivitySourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer weChatCustomerActivitySourceID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    int insert(TWechatCustomerActivitySource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    int insertSelective(TWechatCustomerActivitySource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    List<TWechatCustomerActivitySource> selectByExample(TWechatCustomerActivitySourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    TWechatCustomerActivitySource selectByPrimaryKey(Integer weChatCustomerActivitySourceID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TWechatCustomerActivitySource record, @Param("example") TWechatCustomerActivitySourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TWechatCustomerActivitySource record, @Param("example") TWechatCustomerActivitySourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TWechatCustomerActivitySource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_activity_source
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TWechatCustomerActivitySource record);
}