package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TWeChatCustomer;
import com.warrior.mercury.model.entity.auto.TWeChatCustomerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TWeChatCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    long countByExample(TWeChatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    int deleteByExample(TWeChatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer weChatCustomerID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    int insert(TWeChatCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    int insertSelective(TWeChatCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    List<TWeChatCustomer> selectByExample(TWeChatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    TWeChatCustomer selectByPrimaryKey(Integer weChatCustomerID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TWeChatCustomer record, @Param("example") TWeChatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TWeChatCustomer record, @Param("example") TWeChatCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TWeChatCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TWeChatCustomer record);
}