package com.warrior.mercury.mapper.auto;

import com.warrior.mercury.model.entity.auto.TWechatPurpose;
import com.warrior.mercury.model.entity.auto.TWechatPurposeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TWechatPurposeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    long countByExample(TWechatPurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    int deleteByExample(TWechatPurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer wechatPurposeID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    int insert(TWechatPurpose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    int insertSelective(TWechatPurpose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    List<TWechatPurpose> selectByExample(TWechatPurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    TWechatPurpose selectByPrimaryKey(Integer wechatPurposeID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TWechatPurpose record, @Param("example") TWechatPurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TWechatPurpose record, @Param("example") TWechatPurposeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TWechatPurpose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TWechatPurpose record);
}