server:
  port: 9000

logging:
  config: "classpath:log4j2.xml"

spring:
  application:
    name: warrior

  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #全局json返回配置, 默认不返回为null的字段
  jackson:
    default-property-inclusion: non_null

  #spring-security配置
  security:
    basic:
      enabled: false


  #设置静态资源路径，多个以逗号分隔
  resources:
    static-locations: classpath:static/,file:static/
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  #thymeleaf
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    content-type: text/html
    prefix: classpath:/templates/

  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/resources

#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #支持驼峰命名自动映射
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - "classpath*:mapper/**/*.xml"
  type-aliases-package: tk.mybatis.springboot.model


#mapper:
#  mappers:
#    - tk.mybatis.springboot.util.MyMapper
#  not-empty: false
#  identity: MYSQL

#mybatis-page
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



