server:
  port: 9000

logging:
  config: "classpath:log4j2.xml"

spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #设置静态资源路径，多个以逗号分隔
  resources:
    static-locations: classpath:static/,file:static/
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  #thymeleaf
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    content-type: text/html
    prefix: classpath:/templates/

  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/resources
      #classpath目录下的WEB-INF文件夹内容修改不重启
#      spring.devtools.restart.exclude: WEB-INF/**

#  mvc:
#    view:
#      prefix: classpath:templates/
#      suffix: .html

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #支持驼峰命名自动映射
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - "classpath*:mapper/**/*.xml"




