package com.warrior.mercury.model.entity.auto;

import java.util.ArrayList;
import java.util.List;

public class TOperationWechatExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public TOperationWechatExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOperationWechatIDIsNull() {
            addCriterion("OperationWechatID is null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDIsNotNull() {
            addCriterion("OperationWechatID is not null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDEqualTo(Integer value) {
            addCriterion("OperationWechatID =", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDNotEqualTo(Integer value) {
            addCriterion("OperationWechatID <>", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDGreaterThan(Integer value) {
            addCriterion("OperationWechatID >", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatID >=", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDLessThan(Integer value) {
            addCriterion("OperationWechatID <", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDLessThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatID <=", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDIn(List<Integer> values) {
            addCriterion("OperationWechatID in", values, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDNotIn(List<Integer> values) {
            addCriterion("OperationWechatID not in", values, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatID between", value1, value2, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDNotBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatID not between", value1, value2, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andWechatNoIsNull() {
            addCriterion("WechatNo is null");
            return (Criteria) this;
        }

        public Criteria andWechatNoIsNotNull() {
            addCriterion("WechatNo is not null");
            return (Criteria) this;
        }

        public Criteria andWechatNoEqualTo(String value) {
            addCriterion("WechatNo =", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoNotEqualTo(String value) {
            addCriterion("WechatNo <>", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoGreaterThan(String value) {
            addCriterion("WechatNo >", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoGreaterThanOrEqualTo(String value) {
            addCriterion("WechatNo >=", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoLessThan(String value) {
            addCriterion("WechatNo <", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoLessThanOrEqualTo(String value) {
            addCriterion("WechatNo <=", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoLike(String value) {
            addCriterion("WechatNo like", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoNotLike(String value) {
            addCriterion("WechatNo not like", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoIn(List<String> values) {
            addCriterion("WechatNo in", values, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoNotIn(List<String> values) {
            addCriterion("WechatNo not in", values, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoBetween(String value1, String value2) {
            addCriterion("WechatNo between", value1, value2, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoNotBetween(String value1, String value2) {
            addCriterion("WechatNo not between", value1, value2, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatIDIsNull() {
            addCriterion("WechatID is null");
            return (Criteria) this;
        }

        public Criteria andWechatIDIsNotNull() {
            addCriterion("WechatID is not null");
            return (Criteria) this;
        }

        public Criteria andWechatIDEqualTo(String value) {
            addCriterion("WechatID =", value, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDNotEqualTo(String value) {
            addCriterion("WechatID <>", value, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDGreaterThan(String value) {
            addCriterion("WechatID >", value, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDGreaterThanOrEqualTo(String value) {
            addCriterion("WechatID >=", value, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDLessThan(String value) {
            addCriterion("WechatID <", value, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDLessThanOrEqualTo(String value) {
            addCriterion("WechatID <=", value, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDLike(String value) {
            addCriterion("WechatID like", value, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDNotLike(String value) {
            addCriterion("WechatID not like", value, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDIn(List<String> values) {
            addCriterion("WechatID in", values, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDNotIn(List<String> values) {
            addCriterion("WechatID not in", values, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDBetween(String value1, String value2) {
            addCriterion("WechatID between", value1, value2, "wechatID");
            return (Criteria) this;
        }

        public Criteria andWechatIDNotBetween(String value1, String value2) {
            addCriterion("WechatID not between", value1, value2, "wechatID");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("Nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("Nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("Nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("Nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("Nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("Nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("Nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("Nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("Nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("Nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("Nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("Nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("Nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("Nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeIsNull() {
            addCriterion("AppliedDateTime is null");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeIsNotNull() {
            addCriterion("AppliedDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeEqualTo(String value) {
            addCriterion("AppliedDateTime =", value, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeNotEqualTo(String value) {
            addCriterion("AppliedDateTime <>", value, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeGreaterThan(String value) {
            addCriterion("AppliedDateTime >", value, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("AppliedDateTime >=", value, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeLessThan(String value) {
            addCriterion("AppliedDateTime <", value, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeLessThanOrEqualTo(String value) {
            addCriterion("AppliedDateTime <=", value, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeLike(String value) {
            addCriterion("AppliedDateTime like", value, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeNotLike(String value) {
            addCriterion("AppliedDateTime not like", value, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeIn(List<String> values) {
            addCriterion("AppliedDateTime in", values, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeNotIn(List<String> values) {
            addCriterion("AppliedDateTime not in", values, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeBetween(String value1, String value2) {
            addCriterion("AppliedDateTime between", value1, value2, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedDateTimeNotBetween(String value1, String value2) {
            addCriterion("AppliedDateTime not between", value1, value2, "appliedDateTime");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationIsNull() {
            addCriterion("AppliedLocation is null");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationIsNotNull() {
            addCriterion("AppliedLocation is not null");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationEqualTo(String value) {
            addCriterion("AppliedLocation =", value, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationNotEqualTo(String value) {
            addCriterion("AppliedLocation <>", value, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationGreaterThan(String value) {
            addCriterion("AppliedLocation >", value, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationGreaterThanOrEqualTo(String value) {
            addCriterion("AppliedLocation >=", value, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationLessThan(String value) {
            addCriterion("AppliedLocation <", value, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationLessThanOrEqualTo(String value) {
            addCriterion("AppliedLocation <=", value, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationLike(String value) {
            addCriterion("AppliedLocation like", value, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationNotLike(String value) {
            addCriterion("AppliedLocation not like", value, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationIn(List<String> values) {
            addCriterion("AppliedLocation in", values, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationNotIn(List<String> values) {
            addCriterion("AppliedLocation not in", values, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationBetween(String value1, String value2) {
            addCriterion("AppliedLocation between", value1, value2, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andAppliedLocationNotBetween(String value1, String value2) {
            addCriterion("AppliedLocation not between", value1, value2, "appliedLocation");
            return (Criteria) this;
        }

        public Criteria andApplicantIsNull() {
            addCriterion("Applicant is null");
            return (Criteria) this;
        }

        public Criteria andApplicantIsNotNull() {
            addCriterion("Applicant is not null");
            return (Criteria) this;
        }

        public Criteria andApplicantEqualTo(String value) {
            addCriterion("Applicant =", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantNotEqualTo(String value) {
            addCriterion("Applicant <>", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantGreaterThan(String value) {
            addCriterion("Applicant >", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantGreaterThanOrEqualTo(String value) {
            addCriterion("Applicant >=", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantLessThan(String value) {
            addCriterion("Applicant <", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantLessThanOrEqualTo(String value) {
            addCriterion("Applicant <=", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantLike(String value) {
            addCriterion("Applicant like", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantNotLike(String value) {
            addCriterion("Applicant not like", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantIn(List<String> values) {
            addCriterion("Applicant in", values, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantNotIn(List<String> values) {
            addCriterion("Applicant not in", values, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantBetween(String value1, String value2) {
            addCriterion("Applicant between", value1, value2, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantNotBetween(String value1, String value2) {
            addCriterion("Applicant not between", value1, value2, "applicant");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_wechat
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}