package com.warrior.mercury.model.entity.auto;

import java.io.Serializable;

public class TOperationWechat implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat.OperationWechatID
     *
     * @mbg.generated
     */
    private Integer operationWechatID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat.WechatNo
     *
     * @mbg.generated
     */
    private String wechatNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat.WechatID
     *
     * @mbg.generated
     */
    private String wechatID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat.Nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat.AppliedDateTime
     *
     * @mbg.generated
     */
    private String appliedDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat.AppliedLocation
     *
     * @mbg.generated
     */
    private String appliedLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat.Applicant
     *
     * @mbg.generated
     */
    private String applicant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat.Remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat.OperationWechatID
     *
     * @return the value of t_operation_wechat.OperationWechatID
     *
     * @mbg.generated
     */
    public Integer getOperationWechatID() {
        return operationWechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat.OperationWechatID
     *
     * @param operationWechatID the value for t_operation_wechat.OperationWechatID
     *
     * @mbg.generated
     */
    public void setOperationWechatID(Integer operationWechatID) {
        this.operationWechatID = operationWechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat.WechatNo
     *
     * @return the value of t_operation_wechat.WechatNo
     *
     * @mbg.generated
     */
    public String getWechatNo() {
        return wechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat.WechatNo
     *
     * @param wechatNo the value for t_operation_wechat.WechatNo
     *
     * @mbg.generated
     */
    public void setWechatNo(String wechatNo) {
        this.wechatNo = wechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat.WechatID
     *
     * @return the value of t_operation_wechat.WechatID
     *
     * @mbg.generated
     */
    public String getWechatID() {
        return wechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat.WechatID
     *
     * @param wechatID the value for t_operation_wechat.WechatID
     *
     * @mbg.generated
     */
    public void setWechatID(String wechatID) {
        this.wechatID = wechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat.Nickname
     *
     * @return the value of t_operation_wechat.Nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat.Nickname
     *
     * @param nickname the value for t_operation_wechat.Nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat.AppliedDateTime
     *
     * @return the value of t_operation_wechat.AppliedDateTime
     *
     * @mbg.generated
     */
    public String getAppliedDateTime() {
        return appliedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat.AppliedDateTime
     *
     * @param appliedDateTime the value for t_operation_wechat.AppliedDateTime
     *
     * @mbg.generated
     */
    public void setAppliedDateTime(String appliedDateTime) {
        this.appliedDateTime = appliedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat.AppliedLocation
     *
     * @return the value of t_operation_wechat.AppliedLocation
     *
     * @mbg.generated
     */
    public String getAppliedLocation() {
        return appliedLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat.AppliedLocation
     *
     * @param appliedLocation the value for t_operation_wechat.AppliedLocation
     *
     * @mbg.generated
     */
    public void setAppliedLocation(String appliedLocation) {
        this.appliedLocation = appliedLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat.Applicant
     *
     * @return the value of t_operation_wechat.Applicant
     *
     * @mbg.generated
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat.Applicant
     *
     * @param applicant the value for t_operation_wechat.Applicant
     *
     * @mbg.generated
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat.Remark
     *
     * @return the value of t_operation_wechat.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat.Remark
     *
     * @param remark the value for t_operation_wechat.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", operationWechatID=").append(operationWechatID);
        sb.append(", wechatNo=").append(wechatNo);
        sb.append(", wechatID=").append(wechatID);
        sb.append(", nickname=").append(nickname);
        sb.append(", appliedDateTime=").append(appliedDateTime);
        sb.append(", appliedLocation=").append(appliedLocation);
        sb.append(", applicant=").append(applicant);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}