package com.warrior.mercury.model.entity.auto;

import java.util.ArrayList;
import java.util.List;

public class TOperationWechatUsingLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public TOperationWechatUsingLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOperationWechatUsingLogIDIsNull() {
            addCriterion("OperationWechatUsingLogID is null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDIsNotNull() {
            addCriterion("OperationWechatUsingLogID is not null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDEqualTo(Integer value) {
            addCriterion("OperationWechatUsingLogID =", value, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDNotEqualTo(Integer value) {
            addCriterion("OperationWechatUsingLogID <>", value, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDGreaterThan(Integer value) {
            addCriterion("OperationWechatUsingLogID >", value, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatUsingLogID >=", value, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDLessThan(Integer value) {
            addCriterion("OperationWechatUsingLogID <", value, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDLessThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatUsingLogID <=", value, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDIn(List<Integer> values) {
            addCriterion("OperationWechatUsingLogID in", values, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDNotIn(List<Integer> values) {
            addCriterion("OperationWechatUsingLogID not in", values, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatUsingLogID between", value1, value2, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatUsingLogIDNotBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatUsingLogID not between", value1, value2, "operationWechatUsingLogID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDIsNull() {
            addCriterion("OperationWechatID is null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDIsNotNull() {
            addCriterion("OperationWechatID is not null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDEqualTo(Integer value) {
            addCriterion("OperationWechatID =", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDNotEqualTo(Integer value) {
            addCriterion("OperationWechatID <>", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDGreaterThan(Integer value) {
            addCriterion("OperationWechatID >", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatID >=", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDLessThan(Integer value) {
            addCriterion("OperationWechatID <", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDLessThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatID <=", value, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDIn(List<Integer> values) {
            addCriterion("OperationWechatID in", values, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDNotIn(List<Integer> values) {
            addCriterion("OperationWechatID not in", values, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatID between", value1, value2, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatIDNotBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatID not between", value1, value2, "operationWechatID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDIsNull() {
            addCriterion("OperationWechatStateID is null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDIsNotNull() {
            addCriterion("OperationWechatStateID is not null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDEqualTo(Integer value) {
            addCriterion("OperationWechatStateID =", value, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDNotEqualTo(Integer value) {
            addCriterion("OperationWechatStateID <>", value, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDGreaterThan(Integer value) {
            addCriterion("OperationWechatStateID >", value, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatStateID >=", value, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDLessThan(Integer value) {
            addCriterion("OperationWechatStateID <", value, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDLessThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatStateID <=", value, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDIn(List<Integer> values) {
            addCriterion("OperationWechatStateID in", values, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDNotIn(List<Integer> values) {
            addCriterion("OperationWechatStateID not in", values, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatStateID between", value1, value2, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatStateIDNotBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatStateID not between", value1, value2, "operationWechatStateID");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsIsNull() {
            addCriterion("ResearchFields is null");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsIsNotNull() {
            addCriterion("ResearchFields is not null");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsEqualTo(String value) {
            addCriterion("ResearchFields =", value, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsNotEqualTo(String value) {
            addCriterion("ResearchFields <>", value, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsGreaterThan(String value) {
            addCriterion("ResearchFields >", value, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsGreaterThanOrEqualTo(String value) {
            addCriterion("ResearchFields >=", value, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsLessThan(String value) {
            addCriterion("ResearchFields <", value, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsLessThanOrEqualTo(String value) {
            addCriterion("ResearchFields <=", value, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsLike(String value) {
            addCriterion("ResearchFields like", value, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsNotLike(String value) {
            addCriterion("ResearchFields not like", value, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsIn(List<String> values) {
            addCriterion("ResearchFields in", values, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsNotIn(List<String> values) {
            addCriterion("ResearchFields not in", values, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsBetween(String value1, String value2) {
            addCriterion("ResearchFields between", value1, value2, "researchFields");
            return (Criteria) this;
        }

        public Criteria andResearchFieldsNotBetween(String value1, String value2) {
            addCriterion("ResearchFields not between", value1, value2, "researchFields");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordIsNull() {
            addCriterion("LoginPassword is null");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordIsNotNull() {
            addCriterion("LoginPassword is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordEqualTo(String value) {
            addCriterion("LoginPassword =", value, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordNotEqualTo(String value) {
            addCriterion("LoginPassword <>", value, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordGreaterThan(String value) {
            addCriterion("LoginPassword >", value, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("LoginPassword >=", value, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordLessThan(String value) {
            addCriterion("LoginPassword <", value, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordLessThanOrEqualTo(String value) {
            addCriterion("LoginPassword <=", value, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordLike(String value) {
            addCriterion("LoginPassword like", value, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordNotLike(String value) {
            addCriterion("LoginPassword not like", value, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordIn(List<String> values) {
            addCriterion("LoginPassword in", values, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordNotIn(List<String> values) {
            addCriterion("LoginPassword not in", values, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordBetween(String value1, String value2) {
            addCriterion("LoginPassword between", value1, value2, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andLoginPasswordNotBetween(String value1, String value2) {
            addCriterion("LoginPassword not between", value1, value2, "loginPassword");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationIsNull() {
            addCriterion("IsRealNameAuthentication is null");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationIsNotNull() {
            addCriterion("IsRealNameAuthentication is not null");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationEqualTo(Byte value) {
            addCriterion("IsRealNameAuthentication =", value, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationNotEqualTo(Byte value) {
            addCriterion("IsRealNameAuthentication <>", value, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationGreaterThan(Byte value) {
            addCriterion("IsRealNameAuthentication >", value, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationGreaterThanOrEqualTo(Byte value) {
            addCriterion("IsRealNameAuthentication >=", value, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationLessThan(Byte value) {
            addCriterion("IsRealNameAuthentication <", value, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationLessThanOrEqualTo(Byte value) {
            addCriterion("IsRealNameAuthentication <=", value, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationIn(List<Byte> values) {
            addCriterion("IsRealNameAuthentication in", values, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationNotIn(List<Byte> values) {
            addCriterion("IsRealNameAuthentication not in", values, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationBetween(Byte value1, Byte value2) {
            addCriterion("IsRealNameAuthentication between", value1, value2, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andIsRealNameAuthenticationNotBetween(Byte value1, Byte value2) {
            addCriterion("IsRealNameAuthentication not between", value1, value2, "isRealNameAuthentication");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("RealName is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("RealName is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("RealName =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("RealName <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("RealName >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("RealName >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("RealName <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("RealName <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("RealName like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("RealName not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("RealName in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("RealName not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("RealName between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("RealName not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andBankCardIsNull() {
            addCriterion("BankCard is null");
            return (Criteria) this;
        }

        public Criteria andBankCardIsNotNull() {
            addCriterion("BankCard is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardEqualTo(String value) {
            addCriterion("BankCard =", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardNotEqualTo(String value) {
            addCriterion("BankCard <>", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardGreaterThan(String value) {
            addCriterion("BankCard >", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardGreaterThanOrEqualTo(String value) {
            addCriterion("BankCard >=", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardLessThan(String value) {
            addCriterion("BankCard <", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardLessThanOrEqualTo(String value) {
            addCriterion("BankCard <=", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardLike(String value) {
            addCriterion("BankCard like", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardNotLike(String value) {
            addCriterion("BankCard not like", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardIn(List<String> values) {
            addCriterion("BankCard in", values, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardNotIn(List<String> values) {
            addCriterion("BankCard not in", values, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardBetween(String value1, String value2) {
            addCriterion("BankCard between", value1, value2, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardNotBetween(String value1, String value2) {
            addCriterion("BankCard not between", value1, value2, "bankCard");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordIsNull() {
            addCriterion("PaymentPassword is null");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordIsNotNull() {
            addCriterion("PaymentPassword is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordEqualTo(String value) {
            addCriterion("PaymentPassword =", value, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordNotEqualTo(String value) {
            addCriterion("PaymentPassword <>", value, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordGreaterThan(String value) {
            addCriterion("PaymentPassword >", value, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PaymentPassword >=", value, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordLessThan(String value) {
            addCriterion("PaymentPassword <", value, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordLessThanOrEqualTo(String value) {
            addCriterion("PaymentPassword <=", value, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordLike(String value) {
            addCriterion("PaymentPassword like", value, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordNotLike(String value) {
            addCriterion("PaymentPassword not like", value, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordIn(List<String> values) {
            addCriterion("PaymentPassword in", values, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordNotIn(List<String> values) {
            addCriterion("PaymentPassword not in", values, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordBetween(String value1, String value2) {
            addCriterion("PaymentPassword between", value1, value2, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andPaymentPasswordNotBetween(String value1, String value2) {
            addCriterion("PaymentPassword not between", value1, value2, "paymentPassword");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDIsNull() {
            addCriterion("WechatPurposeID is null");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDIsNotNull() {
            addCriterion("WechatPurposeID is not null");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDEqualTo(Integer value) {
            addCriterion("WechatPurposeID =", value, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDNotEqualTo(Integer value) {
            addCriterion("WechatPurposeID <>", value, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDGreaterThan(Integer value) {
            addCriterion("WechatPurposeID >", value, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("WechatPurposeID >=", value, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDLessThan(Integer value) {
            addCriterion("WechatPurposeID <", value, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDLessThanOrEqualTo(Integer value) {
            addCriterion("WechatPurposeID <=", value, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDIn(List<Integer> values) {
            addCriterion("WechatPurposeID in", values, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDNotIn(List<Integer> values) {
            addCriterion("WechatPurposeID not in", values, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDBetween(Integer value1, Integer value2) {
            addCriterion("WechatPurposeID between", value1, value2, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andWechatPurposeIDNotBetween(Integer value1, Integer value2) {
            addCriterion("WechatPurposeID not between", value1, value2, "wechatPurposeID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDIsNull() {
            addCriterion("OperationWechatPersonID is null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDIsNotNull() {
            addCriterion("OperationWechatPersonID is not null");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDEqualTo(Integer value) {
            addCriterion("OperationWechatPersonID =", value, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDNotEqualTo(Integer value) {
            addCriterion("OperationWechatPersonID <>", value, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDGreaterThan(Integer value) {
            addCriterion("OperationWechatPersonID >", value, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatPersonID >=", value, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDLessThan(Integer value) {
            addCriterion("OperationWechatPersonID <", value, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDLessThanOrEqualTo(Integer value) {
            addCriterion("OperationWechatPersonID <=", value, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDIn(List<Integer> values) {
            addCriterion("OperationWechatPersonID in", values, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDNotIn(List<Integer> values) {
            addCriterion("OperationWechatPersonID not in", values, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatPersonID between", value1, value2, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andOperationWechatPersonIDNotBetween(Integer value1, Integer value2) {
            addCriterion("OperationWechatPersonID not between", value1, value2, "operationWechatPersonID");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeIsNull() {
            addCriterion("CreatedDateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeIsNotNull() {
            addCriterion("CreatedDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeEqualTo(String value) {
            addCriterion("CreatedDateTime =", value, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeNotEqualTo(String value) {
            addCriterion("CreatedDateTime <>", value, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeGreaterThan(String value) {
            addCriterion("CreatedDateTime >", value, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedDateTime >=", value, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeLessThan(String value) {
            addCriterion("CreatedDateTime <", value, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeLessThanOrEqualTo(String value) {
            addCriterion("CreatedDateTime <=", value, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeLike(String value) {
            addCriterion("CreatedDateTime like", value, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeNotLike(String value) {
            addCriterion("CreatedDateTime not like", value, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeIn(List<String> values) {
            addCriterion("CreatedDateTime in", values, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeNotIn(List<String> values) {
            addCriterion("CreatedDateTime not in", values, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeBetween(String value1, String value2) {
            addCriterion("CreatedDateTime between", value1, value2, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andCreatedDateTimeNotBetween(String value1, String value2) {
            addCriterion("CreatedDateTime not between", value1, value2, "createdDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeIsNull() {
            addCriterion("StartedDateTime is null");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeIsNotNull() {
            addCriterion("StartedDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeEqualTo(String value) {
            addCriterion("StartedDateTime =", value, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeNotEqualTo(String value) {
            addCriterion("StartedDateTime <>", value, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeGreaterThan(String value) {
            addCriterion("StartedDateTime >", value, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("StartedDateTime >=", value, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeLessThan(String value) {
            addCriterion("StartedDateTime <", value, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeLessThanOrEqualTo(String value) {
            addCriterion("StartedDateTime <=", value, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeLike(String value) {
            addCriterion("StartedDateTime like", value, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeNotLike(String value) {
            addCriterion("StartedDateTime not like", value, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeIn(List<String> values) {
            addCriterion("StartedDateTime in", values, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeNotIn(List<String> values) {
            addCriterion("StartedDateTime not in", values, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeBetween(String value1, String value2) {
            addCriterion("StartedDateTime between", value1, value2, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andStartedDateTimeNotBetween(String value1, String value2) {
            addCriterion("StartedDateTime not between", value1, value2, "startedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeIsNull() {
            addCriterion("EndedDateTime is null");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeIsNotNull() {
            addCriterion("EndedDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeEqualTo(String value) {
            addCriterion("EndedDateTime =", value, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeNotEqualTo(String value) {
            addCriterion("EndedDateTime <>", value, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeGreaterThan(String value) {
            addCriterion("EndedDateTime >", value, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("EndedDateTime >=", value, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeLessThan(String value) {
            addCriterion("EndedDateTime <", value, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeLessThanOrEqualTo(String value) {
            addCriterion("EndedDateTime <=", value, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeLike(String value) {
            addCriterion("EndedDateTime like", value, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeNotLike(String value) {
            addCriterion("EndedDateTime not like", value, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeIn(List<String> values) {
            addCriterion("EndedDateTime in", values, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeNotIn(List<String> values) {
            addCriterion("EndedDateTime not in", values, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeBetween(String value1, String value2) {
            addCriterion("EndedDateTime between", value1, value2, "endedDateTime");
            return (Criteria) this;
        }

        public Criteria andEndedDateTimeNotBetween(String value1, String value2) {
            addCriterion("EndedDateTime not between", value1, value2, "endedDateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}