package com.warrior.mercury.model.entity.auto;

import java.io.Serializable;

public class TOperationWechatUsingLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.OperationWechatUsingLogID
     *
     * @mbg.generated
     */
    private Integer operationWechatUsingLogID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.OperationWechatID
     *
     * @mbg.generated
     */
    private Integer operationWechatID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.OperationWechatStateID
     *
     * @mbg.generated
     */
    private Integer operationWechatStateID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.ResearchFields
     *
     * @mbg.generated
     */
    private String researchFields;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.LoginPassword
     *
     * @mbg.generated
     */
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.IsRealNameAuthentication
     *
     * @mbg.generated
     */
    private Byte isRealNameAuthentication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.RealName
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.BankCard
     *
     * @mbg.generated
     */
    private String bankCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.PaymentPassword
     *
     * @mbg.generated
     */
    private String paymentPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.WechatPurposeID
     *
     * @mbg.generated
     */
    private Integer wechatPurposeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.OperationWechatPersonID
     *
     * @mbg.generated
     */
    private Integer operationWechatPersonID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.CreatedDateTime
     *
     * @mbg.generated
     */
    private String createdDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.StartedDateTime
     *
     * @mbg.generated
     */
    private String startedDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_wechat_using_log.EndedDateTime
     *
     * @mbg.generated
     */
    private String endedDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.OperationWechatUsingLogID
     *
     * @return the value of t_operation_wechat_using_log.OperationWechatUsingLogID
     *
     * @mbg.generated
     */
    public Integer getOperationWechatUsingLogID() {
        return operationWechatUsingLogID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.OperationWechatUsingLogID
     *
     * @param operationWechatUsingLogID the value for t_operation_wechat_using_log.OperationWechatUsingLogID
     *
     * @mbg.generated
     */
    public void setOperationWechatUsingLogID(Integer operationWechatUsingLogID) {
        this.operationWechatUsingLogID = operationWechatUsingLogID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.OperationWechatID
     *
     * @return the value of t_operation_wechat_using_log.OperationWechatID
     *
     * @mbg.generated
     */
    public Integer getOperationWechatID() {
        return operationWechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.OperationWechatID
     *
     * @param operationWechatID the value for t_operation_wechat_using_log.OperationWechatID
     *
     * @mbg.generated
     */
    public void setOperationWechatID(Integer operationWechatID) {
        this.operationWechatID = operationWechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.OperationWechatStateID
     *
     * @return the value of t_operation_wechat_using_log.OperationWechatStateID
     *
     * @mbg.generated
     */
    public Integer getOperationWechatStateID() {
        return operationWechatStateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.OperationWechatStateID
     *
     * @param operationWechatStateID the value for t_operation_wechat_using_log.OperationWechatStateID
     *
     * @mbg.generated
     */
    public void setOperationWechatStateID(Integer operationWechatStateID) {
        this.operationWechatStateID = operationWechatStateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.ResearchFields
     *
     * @return the value of t_operation_wechat_using_log.ResearchFields
     *
     * @mbg.generated
     */
    public String getResearchFields() {
        return researchFields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.ResearchFields
     *
     * @param researchFields the value for t_operation_wechat_using_log.ResearchFields
     *
     * @mbg.generated
     */
    public void setResearchFields(String researchFields) {
        this.researchFields = researchFields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.LoginPassword
     *
     * @return the value of t_operation_wechat_using_log.LoginPassword
     *
     * @mbg.generated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.LoginPassword
     *
     * @param loginPassword the value for t_operation_wechat_using_log.LoginPassword
     *
     * @mbg.generated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.IsRealNameAuthentication
     *
     * @return the value of t_operation_wechat_using_log.IsRealNameAuthentication
     *
     * @mbg.generated
     */
    public Byte getIsRealNameAuthentication() {
        return isRealNameAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.IsRealNameAuthentication
     *
     * @param isRealNameAuthentication the value for t_operation_wechat_using_log.IsRealNameAuthentication
     *
     * @mbg.generated
     */
    public void setIsRealNameAuthentication(Byte isRealNameAuthentication) {
        this.isRealNameAuthentication = isRealNameAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.RealName
     *
     * @return the value of t_operation_wechat_using_log.RealName
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.RealName
     *
     * @param realName the value for t_operation_wechat_using_log.RealName
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.BankCard
     *
     * @return the value of t_operation_wechat_using_log.BankCard
     *
     * @mbg.generated
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.BankCard
     *
     * @param bankCard the value for t_operation_wechat_using_log.BankCard
     *
     * @mbg.generated
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.PaymentPassword
     *
     * @return the value of t_operation_wechat_using_log.PaymentPassword
     *
     * @mbg.generated
     */
    public String getPaymentPassword() {
        return paymentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.PaymentPassword
     *
     * @param paymentPassword the value for t_operation_wechat_using_log.PaymentPassword
     *
     * @mbg.generated
     */
    public void setPaymentPassword(String paymentPassword) {
        this.paymentPassword = paymentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.WechatPurposeID
     *
     * @return the value of t_operation_wechat_using_log.WechatPurposeID
     *
     * @mbg.generated
     */
    public Integer getWechatPurposeID() {
        return wechatPurposeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.WechatPurposeID
     *
     * @param wechatPurposeID the value for t_operation_wechat_using_log.WechatPurposeID
     *
     * @mbg.generated
     */
    public void setWechatPurposeID(Integer wechatPurposeID) {
        this.wechatPurposeID = wechatPurposeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.OperationWechatPersonID
     *
     * @return the value of t_operation_wechat_using_log.OperationWechatPersonID
     *
     * @mbg.generated
     */
    public Integer getOperationWechatPersonID() {
        return operationWechatPersonID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.OperationWechatPersonID
     *
     * @param operationWechatPersonID the value for t_operation_wechat_using_log.OperationWechatPersonID
     *
     * @mbg.generated
     */
    public void setOperationWechatPersonID(Integer operationWechatPersonID) {
        this.operationWechatPersonID = operationWechatPersonID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.CreatedDateTime
     *
     * @return the value of t_operation_wechat_using_log.CreatedDateTime
     *
     * @mbg.generated
     */
    public String getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.CreatedDateTime
     *
     * @param createdDateTime the value for t_operation_wechat_using_log.CreatedDateTime
     *
     * @mbg.generated
     */
    public void setCreatedDateTime(String createdDateTime) {
        this.createdDateTime = createdDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.StartedDateTime
     *
     * @return the value of t_operation_wechat_using_log.StartedDateTime
     *
     * @mbg.generated
     */
    public String getStartedDateTime() {
        return startedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.StartedDateTime
     *
     * @param startedDateTime the value for t_operation_wechat_using_log.StartedDateTime
     *
     * @mbg.generated
     */
    public void setStartedDateTime(String startedDateTime) {
        this.startedDateTime = startedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_wechat_using_log.EndedDateTime
     *
     * @return the value of t_operation_wechat_using_log.EndedDateTime
     *
     * @mbg.generated
     */
    public String getEndedDateTime() {
        return endedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_wechat_using_log.EndedDateTime
     *
     * @param endedDateTime the value for t_operation_wechat_using_log.EndedDateTime
     *
     * @mbg.generated
     */
    public void setEndedDateTime(String endedDateTime) {
        this.endedDateTime = endedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_wechat_using_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", operationWechatUsingLogID=").append(operationWechatUsingLogID);
        sb.append(", operationWechatID=").append(operationWechatID);
        sb.append(", operationWechatStateID=").append(operationWechatStateID);
        sb.append(", researchFields=").append(researchFields);
        sb.append(", loginPassword=").append(loginPassword);
        sb.append(", isRealNameAuthentication=").append(isRealNameAuthentication);
        sb.append(", realName=").append(realName);
        sb.append(", bankCard=").append(bankCard);
        sb.append(", paymentPassword=").append(paymentPassword);
        sb.append(", wechatPurposeID=").append(wechatPurposeID);
        sb.append(", operationWechatPersonID=").append(operationWechatPersonID);
        sb.append(", createdDateTime=").append(createdDateTime);
        sb.append(", startedDateTime=").append(startedDateTime);
        sb.append(", endedDateTime=").append(endedDateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}