package com.warrior.mercury.model.entity.auto;

import java.io.Serializable;

public class TPerson implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.PersonID
     *
     * @mbg.generated
     */
    private Integer personID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.FirstName
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.MiddleName
     *
     * @mbg.generated
     */
    private String middleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.LastName
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Affiliation1
     *
     * @mbg.generated
     */
    private String affiliation1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Affiliation2
     *
     * @mbg.generated
     */
    private String affiliation2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Email1
     *
     * @mbg.generated
     */
    private String email1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Email2
     *
     * @mbg.generated
     */
    private String email2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Telephone1
     *
     * @mbg.generated
     */
    private String telephone1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Telephone2
     *
     * @mbg.generated
     */
    private String telephone2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.ZipCode
     *
     * @mbg.generated
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.City
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.StateOrProvince
     *
     * @mbg.generated
     */
    private String stateOrProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Website1
     *
     * @mbg.generated
     */
    private String website1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Website2
     *
     * @mbg.generated
     */
    private String website2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.TitleID
     *
     * @mbg.generated
     */
    private Integer titleID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.DegreeID
     *
     * @mbg.generated
     */
    private Integer degreeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.CountryID
     *
     * @mbg.generated
     */
    private Integer countryID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.GenderID
     *
     * @mbg.generated
     */
    private Integer genderID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.SmallPhotoFileName
     *
     * @mbg.generated
     */
    private String smallPhotoFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.BigPhotoFileName
     *
     * @mbg.generated
     */
    private String bigPhotoFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.MSN
     *
     * @mbg.generated
     */
    private String MSN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.ResearchAreas
     *
     * @mbg.generated
     */
    private String researchAreas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Email1IsReleased
     *
     * @mbg.generated
     */
    private Byte email1IsReleased;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Email2IsReleased
     *
     * @mbg.generated
     */
    private Byte email2IsReleased;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.AcademicTitle
     *
     * @mbg.generated
     */
    private String academicTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.MembershipWebsite
     *
     * @mbg.generated
     */
    private String membershipWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.MembershipWebsiteIsReleased
     *
     * @mbg.generated
     */
    private Byte membershipWebsiteIsReleased;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.CVFileName
     *
     * @mbg.generated
     */
    private String CVFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.SmallPhotoIsConfirmed
     *
     * @mbg.generated
     */
    private Byte smallPhotoIsConfirmed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.LocalFirstName
     *
     * @mbg.generated
     */
    private String localFirstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.LocalLastName
     *
     * @mbg.generated
     */
    private String localLastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.LocalAffiliation1
     *
     * @mbg.generated
     */
    private String localAffiliation1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.LocalLanguageID
     *
     * @mbg.generated
     */
    private Integer localLanguageID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.IsUnUsefulEmail
     *
     * @mbg.generated
     */
    private Byte isUnUsefulEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.Department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.QQ
     *
     * @mbg.generated
     */
    private String QQ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person.WeChat
     *
     * @mbg.generated
     */
    private String weChat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_person
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.PersonID
     *
     * @return the value of t_person.PersonID
     *
     * @mbg.generated
     */
    public Integer getPersonID() {
        return personID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.PersonID
     *
     * @param personID the value for t_person.PersonID
     *
     * @mbg.generated
     */
    public void setPersonID(Integer personID) {
        this.personID = personID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.FirstName
     *
     * @return the value of t_person.FirstName
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.FirstName
     *
     * @param firstName the value for t_person.FirstName
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.MiddleName
     *
     * @return the value of t_person.MiddleName
     *
     * @mbg.generated
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.MiddleName
     *
     * @param middleName the value for t_person.MiddleName
     *
     * @mbg.generated
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.LastName
     *
     * @return the value of t_person.LastName
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.LastName
     *
     * @param lastName the value for t_person.LastName
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Affiliation1
     *
     * @return the value of t_person.Affiliation1
     *
     * @mbg.generated
     */
    public String getAffiliation1() {
        return affiliation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Affiliation1
     *
     * @param affiliation1 the value for t_person.Affiliation1
     *
     * @mbg.generated
     */
    public void setAffiliation1(String affiliation1) {
        this.affiliation1 = affiliation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Affiliation2
     *
     * @return the value of t_person.Affiliation2
     *
     * @mbg.generated
     */
    public String getAffiliation2() {
        return affiliation2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Affiliation2
     *
     * @param affiliation2 the value for t_person.Affiliation2
     *
     * @mbg.generated
     */
    public void setAffiliation2(String affiliation2) {
        this.affiliation2 = affiliation2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Email1
     *
     * @return the value of t_person.Email1
     *
     * @mbg.generated
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Email1
     *
     * @param email1 the value for t_person.Email1
     *
     * @mbg.generated
     */
    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Email2
     *
     * @return the value of t_person.Email2
     *
     * @mbg.generated
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Email2
     *
     * @param email2 the value for t_person.Email2
     *
     * @mbg.generated
     */
    public void setEmail2(String email2) {
        this.email2 = email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Telephone1
     *
     * @return the value of t_person.Telephone1
     *
     * @mbg.generated
     */
    public String getTelephone1() {
        return telephone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Telephone1
     *
     * @param telephone1 the value for t_person.Telephone1
     *
     * @mbg.generated
     */
    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Telephone2
     *
     * @return the value of t_person.Telephone2
     *
     * @mbg.generated
     */
    public String getTelephone2() {
        return telephone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Telephone2
     *
     * @param telephone2 the value for t_person.Telephone2
     *
     * @mbg.generated
     */
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Fax
     *
     * @return the value of t_person.Fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Fax
     *
     * @param fax the value for t_person.Fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Address
     *
     * @return the value of t_person.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Address
     *
     * @param address the value for t_person.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.ZipCode
     *
     * @return the value of t_person.ZipCode
     *
     * @mbg.generated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.ZipCode
     *
     * @param zipCode the value for t_person.ZipCode
     *
     * @mbg.generated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.City
     *
     * @return the value of t_person.City
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.City
     *
     * @param city the value for t_person.City
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.StateOrProvince
     *
     * @return the value of t_person.StateOrProvince
     *
     * @mbg.generated
     */
    public String getStateOrProvince() {
        return stateOrProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.StateOrProvince
     *
     * @param stateOrProvince the value for t_person.StateOrProvince
     *
     * @mbg.generated
     */
    public void setStateOrProvince(String stateOrProvince) {
        this.stateOrProvince = stateOrProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Website1
     *
     * @return the value of t_person.Website1
     *
     * @mbg.generated
     */
    public String getWebsite1() {
        return website1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Website1
     *
     * @param website1 the value for t_person.Website1
     *
     * @mbg.generated
     */
    public void setWebsite1(String website1) {
        this.website1 = website1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Website2
     *
     * @return the value of t_person.Website2
     *
     * @mbg.generated
     */
    public String getWebsite2() {
        return website2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Website2
     *
     * @param website2 the value for t_person.Website2
     *
     * @mbg.generated
     */
    public void setWebsite2(String website2) {
        this.website2 = website2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.TitleID
     *
     * @return the value of t_person.TitleID
     *
     * @mbg.generated
     */
    public Integer getTitleID() {
        return titleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.TitleID
     *
     * @param titleID the value for t_person.TitleID
     *
     * @mbg.generated
     */
    public void setTitleID(Integer titleID) {
        this.titleID = titleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.DegreeID
     *
     * @return the value of t_person.DegreeID
     *
     * @mbg.generated
     */
    public Integer getDegreeID() {
        return degreeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.DegreeID
     *
     * @param degreeID the value for t_person.DegreeID
     *
     * @mbg.generated
     */
    public void setDegreeID(Integer degreeID) {
        this.degreeID = degreeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.CountryID
     *
     * @return the value of t_person.CountryID
     *
     * @mbg.generated
     */
    public Integer getCountryID() {
        return countryID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.CountryID
     *
     * @param countryID the value for t_person.CountryID
     *
     * @mbg.generated
     */
    public void setCountryID(Integer countryID) {
        this.countryID = countryID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.GenderID
     *
     * @return the value of t_person.GenderID
     *
     * @mbg.generated
     */
    public Integer getGenderID() {
        return genderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.GenderID
     *
     * @param genderID the value for t_person.GenderID
     *
     * @mbg.generated
     */
    public void setGenderID(Integer genderID) {
        this.genderID = genderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.SmallPhotoFileName
     *
     * @return the value of t_person.SmallPhotoFileName
     *
     * @mbg.generated
     */
    public String getSmallPhotoFileName() {
        return smallPhotoFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.SmallPhotoFileName
     *
     * @param smallPhotoFileName the value for t_person.SmallPhotoFileName
     *
     * @mbg.generated
     */
    public void setSmallPhotoFileName(String smallPhotoFileName) {
        this.smallPhotoFileName = smallPhotoFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.BigPhotoFileName
     *
     * @return the value of t_person.BigPhotoFileName
     *
     * @mbg.generated
     */
    public String getBigPhotoFileName() {
        return bigPhotoFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.BigPhotoFileName
     *
     * @param bigPhotoFileName the value for t_person.BigPhotoFileName
     *
     * @mbg.generated
     */
    public void setBigPhotoFileName(String bigPhotoFileName) {
        this.bigPhotoFileName = bigPhotoFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.MSN
     *
     * @return the value of t_person.MSN
     *
     * @mbg.generated
     */
    public String getMSN() {
        return MSN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.MSN
     *
     * @param MSN the value for t_person.MSN
     *
     * @mbg.generated
     */
    public void setMSN(String MSN) {
        this.MSN = MSN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.ResearchAreas
     *
     * @return the value of t_person.ResearchAreas
     *
     * @mbg.generated
     */
    public String getResearchAreas() {
        return researchAreas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.ResearchAreas
     *
     * @param researchAreas the value for t_person.ResearchAreas
     *
     * @mbg.generated
     */
    public void setResearchAreas(String researchAreas) {
        this.researchAreas = researchAreas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Email1IsReleased
     *
     * @return the value of t_person.Email1IsReleased
     *
     * @mbg.generated
     */
    public Byte getEmail1IsReleased() {
        return email1IsReleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Email1IsReleased
     *
     * @param email1IsReleased the value for t_person.Email1IsReleased
     *
     * @mbg.generated
     */
    public void setEmail1IsReleased(Byte email1IsReleased) {
        this.email1IsReleased = email1IsReleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Email2IsReleased
     *
     * @return the value of t_person.Email2IsReleased
     *
     * @mbg.generated
     */
    public Byte getEmail2IsReleased() {
        return email2IsReleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Email2IsReleased
     *
     * @param email2IsReleased the value for t_person.Email2IsReleased
     *
     * @mbg.generated
     */
    public void setEmail2IsReleased(Byte email2IsReleased) {
        this.email2IsReleased = email2IsReleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.AcademicTitle
     *
     * @return the value of t_person.AcademicTitle
     *
     * @mbg.generated
     */
    public String getAcademicTitle() {
        return academicTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.AcademicTitle
     *
     * @param academicTitle the value for t_person.AcademicTitle
     *
     * @mbg.generated
     */
    public void setAcademicTitle(String academicTitle) {
        this.academicTitle = academicTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.MembershipWebsite
     *
     * @return the value of t_person.MembershipWebsite
     *
     * @mbg.generated
     */
    public String getMembershipWebsite() {
        return membershipWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.MembershipWebsite
     *
     * @param membershipWebsite the value for t_person.MembershipWebsite
     *
     * @mbg.generated
     */
    public void setMembershipWebsite(String membershipWebsite) {
        this.membershipWebsite = membershipWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.MembershipWebsiteIsReleased
     *
     * @return the value of t_person.MembershipWebsiteIsReleased
     *
     * @mbg.generated
     */
    public Byte getMembershipWebsiteIsReleased() {
        return membershipWebsiteIsReleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.MembershipWebsiteIsReleased
     *
     * @param membershipWebsiteIsReleased the value for t_person.MembershipWebsiteIsReleased
     *
     * @mbg.generated
     */
    public void setMembershipWebsiteIsReleased(Byte membershipWebsiteIsReleased) {
        this.membershipWebsiteIsReleased = membershipWebsiteIsReleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.CVFileName
     *
     * @return the value of t_person.CVFileName
     *
     * @mbg.generated
     */
    public String getCVFileName() {
        return CVFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.CVFileName
     *
     * @param CVFileName the value for t_person.CVFileName
     *
     * @mbg.generated
     */
    public void setCVFileName(String CVFileName) {
        this.CVFileName = CVFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.SmallPhotoIsConfirmed
     *
     * @return the value of t_person.SmallPhotoIsConfirmed
     *
     * @mbg.generated
     */
    public Byte getSmallPhotoIsConfirmed() {
        return smallPhotoIsConfirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.SmallPhotoIsConfirmed
     *
     * @param smallPhotoIsConfirmed the value for t_person.SmallPhotoIsConfirmed
     *
     * @mbg.generated
     */
    public void setSmallPhotoIsConfirmed(Byte smallPhotoIsConfirmed) {
        this.smallPhotoIsConfirmed = smallPhotoIsConfirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.LocalFirstName
     *
     * @return the value of t_person.LocalFirstName
     *
     * @mbg.generated
     */
    public String getLocalFirstName() {
        return localFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.LocalFirstName
     *
     * @param localFirstName the value for t_person.LocalFirstName
     *
     * @mbg.generated
     */
    public void setLocalFirstName(String localFirstName) {
        this.localFirstName = localFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.LocalLastName
     *
     * @return the value of t_person.LocalLastName
     *
     * @mbg.generated
     */
    public String getLocalLastName() {
        return localLastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.LocalLastName
     *
     * @param localLastName the value for t_person.LocalLastName
     *
     * @mbg.generated
     */
    public void setLocalLastName(String localLastName) {
        this.localLastName = localLastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.LocalAffiliation1
     *
     * @return the value of t_person.LocalAffiliation1
     *
     * @mbg.generated
     */
    public String getLocalAffiliation1() {
        return localAffiliation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.LocalAffiliation1
     *
     * @param localAffiliation1 the value for t_person.LocalAffiliation1
     *
     * @mbg.generated
     */
    public void setLocalAffiliation1(String localAffiliation1) {
        this.localAffiliation1 = localAffiliation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.LocalLanguageID
     *
     * @return the value of t_person.LocalLanguageID
     *
     * @mbg.generated
     */
    public Integer getLocalLanguageID() {
        return localLanguageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.LocalLanguageID
     *
     * @param localLanguageID the value for t_person.LocalLanguageID
     *
     * @mbg.generated
     */
    public void setLocalLanguageID(Integer localLanguageID) {
        this.localLanguageID = localLanguageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.IsUnUsefulEmail
     *
     * @return the value of t_person.IsUnUsefulEmail
     *
     * @mbg.generated
     */
    public Byte getIsUnUsefulEmail() {
        return isUnUsefulEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.IsUnUsefulEmail
     *
     * @param isUnUsefulEmail the value for t_person.IsUnUsefulEmail
     *
     * @mbg.generated
     */
    public void setIsUnUsefulEmail(Byte isUnUsefulEmail) {
        this.isUnUsefulEmail = isUnUsefulEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.Department
     *
     * @return the value of t_person.Department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.Department
     *
     * @param department the value for t_person.Department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.QQ
     *
     * @return the value of t_person.QQ
     *
     * @mbg.generated
     */
    public String getQQ() {
        return QQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.QQ
     *
     * @param QQ the value for t_person.QQ
     *
     * @mbg.generated
     */
    public void setQQ(String QQ) {
        this.QQ = QQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person.WeChat
     *
     * @return the value of t_person.WeChat
     *
     * @mbg.generated
     */
    public String getWeChat() {
        return weChat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person.WeChat
     *
     * @param weChat the value for t_person.WeChat
     *
     * @mbg.generated
     */
    public void setWeChat(String weChat) {
        this.weChat = weChat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", personID=").append(personID);
        sb.append(", firstName=").append(firstName);
        sb.append(", middleName=").append(middleName);
        sb.append(", lastName=").append(lastName);
        sb.append(", affiliation1=").append(affiliation1);
        sb.append(", affiliation2=").append(affiliation2);
        sb.append(", email1=").append(email1);
        sb.append(", email2=").append(email2);
        sb.append(", telephone1=").append(telephone1);
        sb.append(", telephone2=").append(telephone2);
        sb.append(", fax=").append(fax);
        sb.append(", address=").append(address);
        sb.append(", zipCode=").append(zipCode);
        sb.append(", city=").append(city);
        sb.append(", stateOrProvince=").append(stateOrProvince);
        sb.append(", website1=").append(website1);
        sb.append(", website2=").append(website2);
        sb.append(", titleID=").append(titleID);
        sb.append(", degreeID=").append(degreeID);
        sb.append(", countryID=").append(countryID);
        sb.append(", genderID=").append(genderID);
        sb.append(", smallPhotoFileName=").append(smallPhotoFileName);
        sb.append(", bigPhotoFileName=").append(bigPhotoFileName);
        sb.append(", MSN=").append(MSN);
        sb.append(", researchAreas=").append(researchAreas);
        sb.append(", email1IsReleased=").append(email1IsReleased);
        sb.append(", email2IsReleased=").append(email2IsReleased);
        sb.append(", academicTitle=").append(academicTitle);
        sb.append(", membershipWebsite=").append(membershipWebsite);
        sb.append(", membershipWebsiteIsReleased=").append(membershipWebsiteIsReleased);
        sb.append(", CVFileName=").append(CVFileName);
        sb.append(", smallPhotoIsConfirmed=").append(smallPhotoIsConfirmed);
        sb.append(", localFirstName=").append(localFirstName);
        sb.append(", localLastName=").append(localLastName);
        sb.append(", localAffiliation1=").append(localAffiliation1);
        sb.append(", localLanguageID=").append(localLanguageID);
        sb.append(", isUnUsefulEmail=").append(isUnUsefulEmail);
        sb.append(", department=").append(department);
        sb.append(", QQ=").append(QQ);
        sb.append(", weChat=").append(weChat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}