package com.warrior.mercury.model.entity.auto;

import java.io.Serializable;

public class TPhonebrand implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonebrand.PhoneBrandID
     *
     * @mbg.generated
     */
    private Integer phoneBrandID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonebrand.BrandName
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonebrand.PhoneBrandID
     *
     * @return the value of t_phonebrand.PhoneBrandID
     *
     * @mbg.generated
     */
    public Integer getPhoneBrandID() {
        return phoneBrandID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonebrand.PhoneBrandID
     *
     * @param phoneBrandID the value for t_phonebrand.PhoneBrandID
     *
     * @mbg.generated
     */
    public void setPhoneBrandID(Integer phoneBrandID) {
        this.phoneBrandID = phoneBrandID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonebrand.BrandName
     *
     * @return the value of t_phonebrand.BrandName
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonebrand.BrandName
     *
     * @param brandName the value for t_phonebrand.BrandName
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonebrand
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", phoneBrandID=").append(phoneBrandID);
        sb.append(", brandName=").append(brandName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}