package com.warrior.mercury.model.entity.auto;

import java.util.ArrayList;
import java.util.List;

public class TPhoneoperatingsystemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public TPhoneoperatingsystemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPhoneOperatingSystemIDIsNull() {
            addCriterion("PhoneOperatingSystemID is null");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDIsNotNull() {
            addCriterion("PhoneOperatingSystemID is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDEqualTo(Integer value) {
            addCriterion("PhoneOperatingSystemID =", value, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDNotEqualTo(Integer value) {
            addCriterion("PhoneOperatingSystemID <>", value, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDGreaterThan(Integer value) {
            addCriterion("PhoneOperatingSystemID >", value, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("PhoneOperatingSystemID >=", value, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDLessThan(Integer value) {
            addCriterion("PhoneOperatingSystemID <", value, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDLessThanOrEqualTo(Integer value) {
            addCriterion("PhoneOperatingSystemID <=", value, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDIn(List<Integer> values) {
            addCriterion("PhoneOperatingSystemID in", values, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDNotIn(List<Integer> values) {
            addCriterion("PhoneOperatingSystemID not in", values, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDBetween(Integer value1, Integer value2) {
            addCriterion("PhoneOperatingSystemID between", value1, value2, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andPhoneOperatingSystemIDNotBetween(Integer value1, Integer value2) {
            addCriterion("PhoneOperatingSystemID not between", value1, value2, "phoneOperatingSystemID");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemIsNull() {
            addCriterion("TypeOfOperatingSystem is null");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemIsNotNull() {
            addCriterion("TypeOfOperatingSystem is not null");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemEqualTo(String value) {
            addCriterion("TypeOfOperatingSystem =", value, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemNotEqualTo(String value) {
            addCriterion("TypeOfOperatingSystem <>", value, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemGreaterThan(String value) {
            addCriterion("TypeOfOperatingSystem >", value, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemGreaterThanOrEqualTo(String value) {
            addCriterion("TypeOfOperatingSystem >=", value, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemLessThan(String value) {
            addCriterion("TypeOfOperatingSystem <", value, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemLessThanOrEqualTo(String value) {
            addCriterion("TypeOfOperatingSystem <=", value, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemLike(String value) {
            addCriterion("TypeOfOperatingSystem like", value, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemNotLike(String value) {
            addCriterion("TypeOfOperatingSystem not like", value, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemIn(List<String> values) {
            addCriterion("TypeOfOperatingSystem in", values, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemNotIn(List<String> values) {
            addCriterion("TypeOfOperatingSystem not in", values, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemBetween(String value1, String value2) {
            addCriterion("TypeOfOperatingSystem between", value1, value2, "typeOfOperatingSystem");
            return (Criteria) this;
        }

        public Criteria andTypeOfOperatingSystemNotBetween(String value1, String value2) {
            addCriterion("TypeOfOperatingSystem not between", value1, value2, "typeOfOperatingSystem");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_phoneoperatingsystem
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}