package com.warrior.mercury.model.entity.auto;

import java.io.Serializable;

public class TPhonenumber implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumber.PhoneNumberID
     *
     * @mbg.generated
     */
    private Integer phoneNumberID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumber.PhoneNumber
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumber.Location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumber.AppliedDateTime
     *
     * @mbg.generated
     */
    private String appliedDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumber.Owner
     *
     * @mbg.generated
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_phonenumber
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumber.PhoneNumberID
     *
     * @return the value of t_phonenumber.PhoneNumberID
     *
     * @mbg.generated
     */
    public Integer getPhoneNumberID() {
        return phoneNumberID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumber.PhoneNumberID
     *
     * @param phoneNumberID the value for t_phonenumber.PhoneNumberID
     *
     * @mbg.generated
     */
    public void setPhoneNumberID(Integer phoneNumberID) {
        this.phoneNumberID = phoneNumberID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumber.PhoneNumber
     *
     * @return the value of t_phonenumber.PhoneNumber
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumber.PhoneNumber
     *
     * @param phoneNumber the value for t_phonenumber.PhoneNumber
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumber.Location
     *
     * @return the value of t_phonenumber.Location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumber.Location
     *
     * @param location the value for t_phonenumber.Location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumber.AppliedDateTime
     *
     * @return the value of t_phonenumber.AppliedDateTime
     *
     * @mbg.generated
     */
    public String getAppliedDateTime() {
        return appliedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumber.AppliedDateTime
     *
     * @param appliedDateTime the value for t_phonenumber.AppliedDateTime
     *
     * @mbg.generated
     */
    public void setAppliedDateTime(String appliedDateTime) {
        this.appliedDateTime = appliedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumber.Owner
     *
     * @return the value of t_phonenumber.Owner
     *
     * @mbg.generated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumber.Owner
     *
     * @param owner the value for t_phonenumber.Owner
     *
     * @mbg.generated
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumber
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", phoneNumberID=").append(phoneNumberID);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", location=").append(location);
        sb.append(", appliedDateTime=").append(appliedDateTime);
        sb.append(", owner=").append(owner);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}