package com.warrior.mercury.model.entity.auto;

import java.io.Serializable;

public class TPhonenumberusinglog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.PhoneNumberUsingLogID
     *
     * @mbg.generated
     */
    private Integer phoneNumberUsingLogID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.PhoneNumberID
     *
     * @mbg.generated
     */
    private Integer phoneNumberID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.PhoneNumberPurposeID
     *
     * @mbg.generated
     */
    private Integer phoneNumberPurposeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.PhoneNumberUserPersonID
     *
     * @mbg.generated
     */
    private Integer phoneNumberUserPersonID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.PackageType
     *
     * @mbg.generated
     */
    private String packageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.PhoneNumberStateID
     *
     * @mbg.generated
     */
    private Integer phoneNumberStateID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.CreatedDateTime
     *
     * @mbg.generated
     */
    private String createdDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.StartedDateTime
     *
     * @mbg.generated
     */
    private String startedDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.EndedDateTime
     *
     * @mbg.generated
     */
    private String endedDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.Remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phonenumberusinglog.ParentPhoneNumberID
     *
     * @mbg.generated
     */
    private Integer parentPhoneNumberID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.PhoneNumberUsingLogID
     *
     * @return the value of t_phonenumberusinglog.PhoneNumberUsingLogID
     *
     * @mbg.generated
     */
    public Integer getPhoneNumberUsingLogID() {
        return phoneNumberUsingLogID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.PhoneNumberUsingLogID
     *
     * @param phoneNumberUsingLogID the value for t_phonenumberusinglog.PhoneNumberUsingLogID
     *
     * @mbg.generated
     */
    public void setPhoneNumberUsingLogID(Integer phoneNumberUsingLogID) {
        this.phoneNumberUsingLogID = phoneNumberUsingLogID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.PhoneNumberID
     *
     * @return the value of t_phonenumberusinglog.PhoneNumberID
     *
     * @mbg.generated
     */
    public Integer getPhoneNumberID() {
        return phoneNumberID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.PhoneNumberID
     *
     * @param phoneNumberID the value for t_phonenumberusinglog.PhoneNumberID
     *
     * @mbg.generated
     */
    public void setPhoneNumberID(Integer phoneNumberID) {
        this.phoneNumberID = phoneNumberID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.PhoneNumberPurposeID
     *
     * @return the value of t_phonenumberusinglog.PhoneNumberPurposeID
     *
     * @mbg.generated
     */
    public Integer getPhoneNumberPurposeID() {
        return phoneNumberPurposeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.PhoneNumberPurposeID
     *
     * @param phoneNumberPurposeID the value for t_phonenumberusinglog.PhoneNumberPurposeID
     *
     * @mbg.generated
     */
    public void setPhoneNumberPurposeID(Integer phoneNumberPurposeID) {
        this.phoneNumberPurposeID = phoneNumberPurposeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.PhoneNumberUserPersonID
     *
     * @return the value of t_phonenumberusinglog.PhoneNumberUserPersonID
     *
     * @mbg.generated
     */
    public Integer getPhoneNumberUserPersonID() {
        return phoneNumberUserPersonID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.PhoneNumberUserPersonID
     *
     * @param phoneNumberUserPersonID the value for t_phonenumberusinglog.PhoneNumberUserPersonID
     *
     * @mbg.generated
     */
    public void setPhoneNumberUserPersonID(Integer phoneNumberUserPersonID) {
        this.phoneNumberUserPersonID = phoneNumberUserPersonID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.PackageType
     *
     * @return the value of t_phonenumberusinglog.PackageType
     *
     * @mbg.generated
     */
    public String getPackageType() {
        return packageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.PackageType
     *
     * @param packageType the value for t_phonenumberusinglog.PackageType
     *
     * @mbg.generated
     */
    public void setPackageType(String packageType) {
        this.packageType = packageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.PhoneNumberStateID
     *
     * @return the value of t_phonenumberusinglog.PhoneNumberStateID
     *
     * @mbg.generated
     */
    public Integer getPhoneNumberStateID() {
        return phoneNumberStateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.PhoneNumberStateID
     *
     * @param phoneNumberStateID the value for t_phonenumberusinglog.PhoneNumberStateID
     *
     * @mbg.generated
     */
    public void setPhoneNumberStateID(Integer phoneNumberStateID) {
        this.phoneNumberStateID = phoneNumberStateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.CreatedDateTime
     *
     * @return the value of t_phonenumberusinglog.CreatedDateTime
     *
     * @mbg.generated
     */
    public String getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.CreatedDateTime
     *
     * @param createdDateTime the value for t_phonenumberusinglog.CreatedDateTime
     *
     * @mbg.generated
     */
    public void setCreatedDateTime(String createdDateTime) {
        this.createdDateTime = createdDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.StartedDateTime
     *
     * @return the value of t_phonenumberusinglog.StartedDateTime
     *
     * @mbg.generated
     */
    public String getStartedDateTime() {
        return startedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.StartedDateTime
     *
     * @param startedDateTime the value for t_phonenumberusinglog.StartedDateTime
     *
     * @mbg.generated
     */
    public void setStartedDateTime(String startedDateTime) {
        this.startedDateTime = startedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.EndedDateTime
     *
     * @return the value of t_phonenumberusinglog.EndedDateTime
     *
     * @mbg.generated
     */
    public String getEndedDateTime() {
        return endedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.EndedDateTime
     *
     * @param endedDateTime the value for t_phonenumberusinglog.EndedDateTime
     *
     * @mbg.generated
     */
    public void setEndedDateTime(String endedDateTime) {
        this.endedDateTime = endedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.Remark
     *
     * @return the value of t_phonenumberusinglog.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.Remark
     *
     * @param remark the value for t_phonenumberusinglog.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phonenumberusinglog.ParentPhoneNumberID
     *
     * @return the value of t_phonenumberusinglog.ParentPhoneNumberID
     *
     * @mbg.generated
     */
    public Integer getParentPhoneNumberID() {
        return parentPhoneNumberID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phonenumberusinglog.ParentPhoneNumberID
     *
     * @param parentPhoneNumberID the value for t_phonenumberusinglog.ParentPhoneNumberID
     *
     * @mbg.generated
     */
    public void setParentPhoneNumberID(Integer parentPhoneNumberID) {
        this.parentPhoneNumberID = parentPhoneNumberID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_phonenumberusinglog
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", phoneNumberUsingLogID=").append(phoneNumberUsingLogID);
        sb.append(", phoneNumberID=").append(phoneNumberID);
        sb.append(", phoneNumberPurposeID=").append(phoneNumberPurposeID);
        sb.append(", phoneNumberUserPersonID=").append(phoneNumberUserPersonID);
        sb.append(", packageType=").append(packageType);
        sb.append(", phoneNumberStateID=").append(phoneNumberStateID);
        sb.append(", createdDateTime=").append(createdDateTime);
        sb.append(", startedDateTime=").append(startedDateTime);
        sb.append(", endedDateTime=").append(endedDateTime);
        sb.append(", remark=").append(remark);
        sb.append(", parentPhoneNumberID=").append(parentPhoneNumberID);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}