package com.warrior.mercury.model.entity.auto;

import java.util.ArrayList;
import java.util.List;

public class TWechatCustomerAddingSourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public TWechatCustomerAddingSourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWeChatCustomerAddingSourceIDIsNull() {
            addCriterion("WeChatCustomerAddingSourceID is null");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDIsNotNull() {
            addCriterion("WeChatCustomerAddingSourceID is not null");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDEqualTo(Integer value) {
            addCriterion("WeChatCustomerAddingSourceID =", value, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDNotEqualTo(Integer value) {
            addCriterion("WeChatCustomerAddingSourceID <>", value, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDGreaterThan(Integer value) {
            addCriterion("WeChatCustomerAddingSourceID >", value, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("WeChatCustomerAddingSourceID >=", value, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDLessThan(Integer value) {
            addCriterion("WeChatCustomerAddingSourceID <", value, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDLessThanOrEqualTo(Integer value) {
            addCriterion("WeChatCustomerAddingSourceID <=", value, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDIn(List<Integer> values) {
            addCriterion("WeChatCustomerAddingSourceID in", values, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDNotIn(List<Integer> values) {
            addCriterion("WeChatCustomerAddingSourceID not in", values, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDBetween(Integer value1, Integer value2) {
            addCriterion("WeChatCustomerAddingSourceID between", value1, value2, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerAddingSourceIDNotBetween(Integer value1, Integer value2) {
            addCriterion("WeChatCustomerAddingSourceID not between", value1, value2, "weChatCustomerAddingSourceID");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("Source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("Source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("Source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("Source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("Source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("Source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("Source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("Source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("Source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("Source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("Source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("Source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("Source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("Source not between", value1, value2, "source");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_wechat_customer_adding_source
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}