package com.warrior.mercury.model.entity.auto;

import java.io.Serializable;

public class TWeChatCustomer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.WeChatCustomerID
     *
     * @mbg.generated
     */
    private Integer weChatCustomerID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.PersonID
     *
     * @mbg.generated
     */
    private String personID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.OriginalWechatID
     *
     * @mbg.generated
     */
    private String originalWechatID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.UpdatedWechatID
     *
     * @mbg.generated
     */
    private String updatedWechatID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.Alias
     *
     * @mbg.generated
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.Tag
     *
     * @mbg.generated
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.WeChatAddedDateTime
     *
     * @mbg.generated
     */
    private String weChatAddedDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.RecordedDateTime
     *
     * @mbg.generated
     */
    private String recordedDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.RecorderID
     *
     * @mbg.generated
     */
    private Integer recorderID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.WeChatCustomerActivitySourceID
     *
     * @mbg.generated
     */
    private Integer weChatCustomerActivitySourceID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.WeChatCustomerAddingSourceID
     *
     * @mbg.generated
     */
    private Integer weChatCustomerAddingSourceID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.TitleID
     *
     * @mbg.generated
     */
    private Integer titleID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.Affiliation
     *
     * @mbg.generated
     */
    private String affiliation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.ResearchFields
     *
     * @mbg.generated
     */
    private String researchFields;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.CustomerPhoneNumber
     *
     * @mbg.generated
     */
    private String customerPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.CommentForCustomer
     *
     * @mbg.generated
     */
    private String commentForCustomer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.WeChatCustomerEvaluationID
     *
     * @mbg.generated
     */
    private Integer weChatCustomerEvaluationID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_we_chat_customer.Remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.WeChatCustomerID
     *
     * @return the value of t_we_chat_customer.WeChatCustomerID
     *
     * @mbg.generated
     */
    public Integer getWeChatCustomerID() {
        return weChatCustomerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.WeChatCustomerID
     *
     * @param weChatCustomerID the value for t_we_chat_customer.WeChatCustomerID
     *
     * @mbg.generated
     */
    public void setWeChatCustomerID(Integer weChatCustomerID) {
        this.weChatCustomerID = weChatCustomerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.PersonID
     *
     * @return the value of t_we_chat_customer.PersonID
     *
     * @mbg.generated
     */
    public String getPersonID() {
        return personID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.PersonID
     *
     * @param personID the value for t_we_chat_customer.PersonID
     *
     * @mbg.generated
     */
    public void setPersonID(String personID) {
        this.personID = personID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.OriginalWechatID
     *
     * @return the value of t_we_chat_customer.OriginalWechatID
     *
     * @mbg.generated
     */
    public String getOriginalWechatID() {
        return originalWechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.OriginalWechatID
     *
     * @param originalWechatID the value for t_we_chat_customer.OriginalWechatID
     *
     * @mbg.generated
     */
    public void setOriginalWechatID(String originalWechatID) {
        this.originalWechatID = originalWechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.UpdatedWechatID
     *
     * @return the value of t_we_chat_customer.UpdatedWechatID
     *
     * @mbg.generated
     */
    public String getUpdatedWechatID() {
        return updatedWechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.UpdatedWechatID
     *
     * @param updatedWechatID the value for t_we_chat_customer.UpdatedWechatID
     *
     * @mbg.generated
     */
    public void setUpdatedWechatID(String updatedWechatID) {
        this.updatedWechatID = updatedWechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.Alias
     *
     * @return the value of t_we_chat_customer.Alias
     *
     * @mbg.generated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.Alias
     *
     * @param alias the value for t_we_chat_customer.Alias
     *
     * @mbg.generated
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.Tag
     *
     * @return the value of t_we_chat_customer.Tag
     *
     * @mbg.generated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.Tag
     *
     * @param tag the value for t_we_chat_customer.Tag
     *
     * @mbg.generated
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.WeChatAddedDateTime
     *
     * @return the value of t_we_chat_customer.WeChatAddedDateTime
     *
     * @mbg.generated
     */
    public String getWeChatAddedDateTime() {
        return weChatAddedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.WeChatAddedDateTime
     *
     * @param weChatAddedDateTime the value for t_we_chat_customer.WeChatAddedDateTime
     *
     * @mbg.generated
     */
    public void setWeChatAddedDateTime(String weChatAddedDateTime) {
        this.weChatAddedDateTime = weChatAddedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.RecordedDateTime
     *
     * @return the value of t_we_chat_customer.RecordedDateTime
     *
     * @mbg.generated
     */
    public String getRecordedDateTime() {
        return recordedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.RecordedDateTime
     *
     * @param recordedDateTime the value for t_we_chat_customer.RecordedDateTime
     *
     * @mbg.generated
     */
    public void setRecordedDateTime(String recordedDateTime) {
        this.recordedDateTime = recordedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.RecorderID
     *
     * @return the value of t_we_chat_customer.RecorderID
     *
     * @mbg.generated
     */
    public Integer getRecorderID() {
        return recorderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.RecorderID
     *
     * @param recorderID the value for t_we_chat_customer.RecorderID
     *
     * @mbg.generated
     */
    public void setRecorderID(Integer recorderID) {
        this.recorderID = recorderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.WeChatCustomerActivitySourceID
     *
     * @return the value of t_we_chat_customer.WeChatCustomerActivitySourceID
     *
     * @mbg.generated
     */
    public Integer getWeChatCustomerActivitySourceID() {
        return weChatCustomerActivitySourceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.WeChatCustomerActivitySourceID
     *
     * @param weChatCustomerActivitySourceID the value for t_we_chat_customer.WeChatCustomerActivitySourceID
     *
     * @mbg.generated
     */
    public void setWeChatCustomerActivitySourceID(Integer weChatCustomerActivitySourceID) {
        this.weChatCustomerActivitySourceID = weChatCustomerActivitySourceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.WeChatCustomerAddingSourceID
     *
     * @return the value of t_we_chat_customer.WeChatCustomerAddingSourceID
     *
     * @mbg.generated
     */
    public Integer getWeChatCustomerAddingSourceID() {
        return weChatCustomerAddingSourceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.WeChatCustomerAddingSourceID
     *
     * @param weChatCustomerAddingSourceID the value for t_we_chat_customer.WeChatCustomerAddingSourceID
     *
     * @mbg.generated
     */
    public void setWeChatCustomerAddingSourceID(Integer weChatCustomerAddingSourceID) {
        this.weChatCustomerAddingSourceID = weChatCustomerAddingSourceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.TitleID
     *
     * @return the value of t_we_chat_customer.TitleID
     *
     * @mbg.generated
     */
    public Integer getTitleID() {
        return titleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.TitleID
     *
     * @param titleID the value for t_we_chat_customer.TitleID
     *
     * @mbg.generated
     */
    public void setTitleID(Integer titleID) {
        this.titleID = titleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.Affiliation
     *
     * @return the value of t_we_chat_customer.Affiliation
     *
     * @mbg.generated
     */
    public String getAffiliation() {
        return affiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.Affiliation
     *
     * @param affiliation the value for t_we_chat_customer.Affiliation
     *
     * @mbg.generated
     */
    public void setAffiliation(String affiliation) {
        this.affiliation = affiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.ResearchFields
     *
     * @return the value of t_we_chat_customer.ResearchFields
     *
     * @mbg.generated
     */
    public String getResearchFields() {
        return researchFields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.ResearchFields
     *
     * @param researchFields the value for t_we_chat_customer.ResearchFields
     *
     * @mbg.generated
     */
    public void setResearchFields(String researchFields) {
        this.researchFields = researchFields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.CustomerPhoneNumber
     *
     * @return the value of t_we_chat_customer.CustomerPhoneNumber
     *
     * @mbg.generated
     */
    public String getCustomerPhoneNumber() {
        return customerPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.CustomerPhoneNumber
     *
     * @param customerPhoneNumber the value for t_we_chat_customer.CustomerPhoneNumber
     *
     * @mbg.generated
     */
    public void setCustomerPhoneNumber(String customerPhoneNumber) {
        this.customerPhoneNumber = customerPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.CommentForCustomer
     *
     * @return the value of t_we_chat_customer.CommentForCustomer
     *
     * @mbg.generated
     */
    public String getCommentForCustomer() {
        return commentForCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.CommentForCustomer
     *
     * @param commentForCustomer the value for t_we_chat_customer.CommentForCustomer
     *
     * @mbg.generated
     */
    public void setCommentForCustomer(String commentForCustomer) {
        this.commentForCustomer = commentForCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.WeChatCustomerEvaluationID
     *
     * @return the value of t_we_chat_customer.WeChatCustomerEvaluationID
     *
     * @mbg.generated
     */
    public Integer getWeChatCustomerEvaluationID() {
        return weChatCustomerEvaluationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.WeChatCustomerEvaluationID
     *
     * @param weChatCustomerEvaluationID the value for t_we_chat_customer.WeChatCustomerEvaluationID
     *
     * @mbg.generated
     */
    public void setWeChatCustomerEvaluationID(Integer weChatCustomerEvaluationID) {
        this.weChatCustomerEvaluationID = weChatCustomerEvaluationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_we_chat_customer.Remark
     *
     * @return the value of t_we_chat_customer.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_we_chat_customer.Remark
     *
     * @param remark the value for t_we_chat_customer.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", weChatCustomerID=").append(weChatCustomerID);
        sb.append(", personID=").append(personID);
        sb.append(", originalWechatID=").append(originalWechatID);
        sb.append(", updatedWechatID=").append(updatedWechatID);
        sb.append(", alias=").append(alias);
        sb.append(", tag=").append(tag);
        sb.append(", weChatAddedDateTime=").append(weChatAddedDateTime);
        sb.append(", recordedDateTime=").append(recordedDateTime);
        sb.append(", recorderID=").append(recorderID);
        sb.append(", weChatCustomerActivitySourceID=").append(weChatCustomerActivitySourceID);
        sb.append(", weChatCustomerAddingSourceID=").append(weChatCustomerAddingSourceID);
        sb.append(", titleID=").append(titleID);
        sb.append(", affiliation=").append(affiliation);
        sb.append(", researchFields=").append(researchFields);
        sb.append(", customerPhoneNumber=").append(customerPhoneNumber);
        sb.append(", commentForCustomer=").append(commentForCustomer);
        sb.append(", weChatCustomerEvaluationID=").append(weChatCustomerEvaluationID);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}