package com.warrior.mercury.model.entity.auto;

import java.util.ArrayList;
import java.util.List;

public class TWeChatCustomerEvaluationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public TWeChatCustomerEvaluationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWeChatCustomerEvaluationIDIsNull() {
            addCriterion("WeChatCustomerEvaluationID is null");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDIsNotNull() {
            addCriterion("WeChatCustomerEvaluationID is not null");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDEqualTo(Integer value) {
            addCriterion("WeChatCustomerEvaluationID =", value, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDNotEqualTo(Integer value) {
            addCriterion("WeChatCustomerEvaluationID <>", value, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDGreaterThan(Integer value) {
            addCriterion("WeChatCustomerEvaluationID >", value, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("WeChatCustomerEvaluationID >=", value, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDLessThan(Integer value) {
            addCriterion("WeChatCustomerEvaluationID <", value, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDLessThanOrEqualTo(Integer value) {
            addCriterion("WeChatCustomerEvaluationID <=", value, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDIn(List<Integer> values) {
            addCriterion("WeChatCustomerEvaluationID in", values, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDNotIn(List<Integer> values) {
            addCriterion("WeChatCustomerEvaluationID not in", values, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDBetween(Integer value1, Integer value2) {
            addCriterion("WeChatCustomerEvaluationID between", value1, value2, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andWeChatCustomerEvaluationIDNotBetween(Integer value1, Integer value2) {
            addCriterion("WeChatCustomerEvaluationID not between", value1, value2, "weChatCustomerEvaluationID");
            return (Criteria) this;
        }

        public Criteria andEvaluationIsNull() {
            addCriterion("Evaluation is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationIsNotNull() {
            addCriterion("Evaluation is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationEqualTo(String value) {
            addCriterion("Evaluation =", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationNotEqualTo(String value) {
            addCriterion("Evaluation <>", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationGreaterThan(String value) {
            addCriterion("Evaluation >", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationGreaterThanOrEqualTo(String value) {
            addCriterion("Evaluation >=", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationLessThan(String value) {
            addCriterion("Evaluation <", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationLessThanOrEqualTo(String value) {
            addCriterion("Evaluation <=", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationLike(String value) {
            addCriterion("Evaluation like", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationNotLike(String value) {
            addCriterion("Evaluation not like", value, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationIn(List<String> values) {
            addCriterion("Evaluation in", values, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationNotIn(List<String> values) {
            addCriterion("Evaluation not in", values, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationBetween(String value1, String value2) {
            addCriterion("Evaluation between", value1, value2, "evaluation");
            return (Criteria) this;
        }

        public Criteria andEvaluationNotBetween(String value1, String value2) {
            addCriterion("Evaluation not between", value1, value2, "evaluation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_we_chat_customer_evaluation
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}