package com.warrior.mercury.model.entity.auto;

import java.io.Serializable;

public class TWechatPurpose implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_purpose.WechatPurposeID
     *
     * @mbg.generated
     */
    private Integer wechatPurposeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_purpose.Purpose
     *
     * @mbg.generated
     */
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_purpose.WechatPurposeID
     *
     * @return the value of t_wechat_purpose.WechatPurposeID
     *
     * @mbg.generated
     */
    public Integer getWechatPurposeID() {
        return wechatPurposeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_purpose.WechatPurposeID
     *
     * @param wechatPurposeID the value for t_wechat_purpose.WechatPurposeID
     *
     * @mbg.generated
     */
    public void setWechatPurposeID(Integer wechatPurposeID) {
        this.wechatPurposeID = wechatPurposeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_purpose.Purpose
     *
     * @return the value of t_wechat_purpose.Purpose
     *
     * @mbg.generated
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_purpose.Purpose
     *
     * @param purpose the value for t_wechat_purpose.Purpose
     *
     * @mbg.generated
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_purpose
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wechatPurposeID=").append(wechatPurposeID);
        sb.append(", purpose=").append(purpose);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}